version: "3.8"

services:
  node:
    build:
      context: ./dockerfiles
      dockerfile: node.dockerfile
    container_name: node-sammy2455
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "2245:3000"
    networks:
      - sammy

networks:
  sammy:
    name: sammy-web-net
    driver: bridge